### ISSUE TITLE
Failed to load cupy

### ISSUE THREAD

**Issue by asterisk37n** [aistairc/abci-user-manual#17]
I loaded modules
``` module load python/3.6 cuda/9.2```
and then created venv, then installed cupy-cuda92, but failed to import cupy.

```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Wed_Apr_11_23:16:29_CDT_2018
Cuda compilation tools, release 9.2, V9.2.88
```

```
$ pip3 freeze
absl-py==0.7.0
astor==0.7.1
chainer==5.2.0
cupy-cuda92==5.2.0
fastrlock==0.4
filelock==3.0.10
gast==0.2.2
grpcio==1.18.0
h5py==2.9.0
imageio==2.5.0
Keras==2.2.4
Keras-Applications==1.0.7
Keras-Preprocessing==1.0.9
Markdown==3.0.1
numpy==1.16.1
Pillow==5.4.1
protobuf==3.6.1
PyYAML==3.13
scikit-learn==0.20.2
scipy==1.2.1
six==1.12.0
sklearn==0.0
tensorboard==1.12.2
tensorflow==1.12.0
termcolor==1.1.0
Werkzeug==0.14.1
```

```
$ python3
Python 3.6.5 (default, Jun  2 2018, 15:49:50) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cupy
Traceback (most recent call last):
  File "/fs3/home/aca10485tl/dl/lib/python3.6/site-packages/cupy/__init__.py", line 11, in <module>
    from cupy import core  # NOQA
  File "/fs3/home/aca10485tl/dl/lib/python3.6/site-packages/cupy/core/__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/fs3/home/aca10485tl/dl/lib/python3.6/site-packages/cupy/__init__.py", line 32, in <module>
    six.reraise(ImportError, ImportError(msg), exc_info[2])
  File "/fs3/home/aca10485tl/dl/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/fs3/home/aca10485tl/dl/lib/python3.6/site-packages/cupy/__init__.py", line 11, in <module>
    from cupy import core  # NOQA
  File "/fs3/home/aca10485tl/dl/lib/python3.6/site-packages/cupy/core/__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
ImportError: CuPy is not correctly installed.

If you are using wheel distribution (cupy-cudaXX), make sure that the version of CuPy you installed matches with the version of CUDA on your host.
Also, confirm that only one CuPy package is installed:
  $ pip freeze

If you are building CuPy from source, please check your environment, uninstall CuPy and reinstall it with:
  $ pip install cupy --no-cache-dir -vvvv

Check the Installation Guide for details:
  https://docs-cupy.chainer.org/en/latest/install.html

original error: libcuda.so.1: cannot open shared object file: No such file or directory
```

**Comment by asterisk37n** [comment]
Cannot create symlink to fix.
```
(dl) [aca10485tl@es3 ~]$ cd /apps/cuda/9.1.85.3/lib64/stubs/
(dl) [aca10485tl@es3 stubs]$ ls
libcublas.so  libcufft.so   libcurand.so    libcusparse.so  libnppial.so  libnppicom.so  libnppif.so  libnppim.so   libnppisu.so  libnpps.so     libnvidia-ml.so
libcuda.so    libcufftw.so  libcusolver.so  libnppc.so      libnppicc.so  libnppidei.so  libnppig.so  libnppist.so  libnppitc.so  libnvgraph.so  libnvrtc.so
(dl) [aca10485tl@es3 stubs]$ ln -s libcuda.so libcuda.so.1
ln: failed to create symbolic link 'libcuda.so.1': Permission denied
```

**Comment by rymzt** [comment]
es[1-4]にはGPUが搭載されておらずlibcuda.soを含めたNVIDIA Driverがインストールされていないため、計算ノードをご利用ください。

**Comment by rymzt** [comment]
また、利用方法に関する質問はqa@abci.aiへメールでお問い合わせください。
下記ページにメール質問のテンプレートが記載されています。
https://abci.ai/ja/how_to_use/user_support.html
